# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch

name: Personal Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_isocalendar: yes
          config_order: base.header, isocalendar, base.repositories

      - name: 🦑 Personal metrics (additional)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c
          plugin_languages_skipped: lowlighter
          plugin_languages_details: bytes-size, percentage
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Europe/Paris
          config_order: languages, pagespeed, habits, stargazers, stars
